server:
  port: 8084

openstack:
  identity:
    url: http://192.168.1.165/identity/v3
    username: admin
    password: secret
    domain:
      name: Default
    project:
      name: admin
  object-storage:
    url: http://192.168.1.165:8080/v1/AUTH_1495c69058174462b73ea23d378c7b37
    container: phyloviz-web-platform

spring:
  data:
    mongodb:
      host: localhost
      port: 28017
      username: root
      password: root
      database: phyloviz-web-platform
      authentication-database: admin
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8082/realms/phyloviz-web-platform/protocol/openid-connect/token/introspect
          client-id: phyloviz-web-platform-client
          client-secret: pZW9kZ05jHjLiOlYYhBAa9CGk1uL7bob

  servlet:
    multipart:
      max-file-size: "100GB"
      max-request-size: "100GB"

logging:
  level:
    org:
      springframework:
        web:
          server:
            adapter:
              AbstractReactiveWebInitializer: DEBUG
        security:
          web: DEBUG
    web: DEBUG
