server:
  port: 8085

spring:
  config:
    import: application-shared.yml

data-repositories:
  get-distance-matrix-repository: S3
  get-tree-repository: PHYLODB
  get-tree-view-repository: PHYLODB

logging:
  level:
    root: debug